app:
  name: MyGoApp
  version: 1.0
  host: http://127.0.0.1:8081/
  hash: EpDYiCD/2g4L2Id0nZKbcroQyRb0qDaf
  token: 26e67818dfa848c2

mysql:
  host: 127.0.0.1
  port: 3306
  charset: utf8mb4
  username: root
  password: 123456
  database: pav
  timeout: 60s
  max_idle_num: 10
  max_open_num: 20
  connect_lifetime: 5 #min

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  pool_size: 10
  timeout: 30